In [1]:
import numpy as np

In [6]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([2,5,8])


In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:

B

array([2, 5, 8])

In [8]:
np.add(A,B)

array([[ 3,  7, 11],
       [ 6, 10, 14],
       [ 9, 13, 17]])

In [9]:
np.subtract(A,B)

array([[-1, -3, -5],
       [ 2,  0, -2],
       [ 5,  3,  1]])

In [10]:
np.multiply(A,B)

array([[ 2, 10, 24],
       [ 8, 25, 48],
       [14, 40, 72]])

In [11]:
np.divide(A,B)

array([[0.5  , 0.4  , 0.375],
       [2.   , 1.   , 0.75 ],
       [3.5  , 1.6  , 1.125]])

In [12]:
np.power(A,B)

array([[       1,       32,     6561],
       [      16,     3125,  1679616],
       [      49,    32768, 43046721]], dtype=int32)