In [1]:
import numpy as np

In [15]:
arr = np.array([x for x in range(3,99,3)])
arr = arr.reshape(4,8)
arr

array([[ 3,  6,  9, 12, 15, 18, 21, 24],
       [27, 30, 33, 36, 39, 42, 45, 48],
       [51, 54, 57, 60, 63, 66, 69, 72],
       [75, 78, 81, 84, 87, 90, 93, 96]])

In [16]:
np.amin(arr)

3

In [18]:
np.amin(arr,axis = 0)

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [19]:
np.amin(arr,axis = 1)

array([ 3, 27, 51, 75])

In [20]:
np.max(arr)

96

In [21]:
np.max(arr, axis = 0)

array([75, 78, 81, 84, 87, 90, 93, 96])

In [22]:
np.max(arr,axis =0)

array([75, 78, 81, 84, 87, 90, 93, 96])

In [23]:
np.min(arr)

3

In [24]:
np.min(arr,axis = 0)

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [25]:
np.min(arr,axis = 1)

array([ 3, 27, 51, 75])

In [26]:
np.median(arr)

49.5

In [27]:
np.mean(arr)

49.5

In [29]:
np.std(arr)

27.69927796892908

In [30]:
np.var(arr)

767.25

In [31]:
np.percentile(arr,20)

21.6

In [32]:
np.percentile(arr,50)

49.5

In [35]:
deg = np.array([x for x in range(0,361, 30)])

In [36]:
np.sin(deg*np.pi/180)

array([ 0.00000000e+00,  5.00000000e-01,  8.66025404e-01,  1.00000000e+00,
        8.66025404e-01,  5.00000000e-01,  1.22464680e-16, -5.00000000e-01,
       -8.66025404e-01, -1.00000000e+00, -8.66025404e-01, -5.00000000e-01,
       -2.44929360e-16])

In [37]:
np.tan(deg*np.pi/180)

array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16,  5.77350269e-01,
        1.73205081e+00,  5.44374645e+15, -1.73205081e+00, -5.77350269e-01,
       -2.44929360e-16])