In [1]:
import numpy as np

In [10]:
np_array = np.array([x for x in range(2,26,2)])
np_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [12]:
# Convert 1D array to multidimensional array
np_array.reshape(3,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [13]:
# Convert 1D array to multidimensional array
np_array.reshape(3,2,2)

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [14]:
# Convert Multi-simensional array to 1D array
np_array.flatten()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])